spring:
  datasource:
    url: jdbc:h2:mem:lg-test
    username: lg
    password: laundryGo!
    hikari:
      maximum-pool-size: 4
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE